//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominikStiller.VertretungsplanUploader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DominikStiller.VertretungsplanUploader.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie das Programm wirklich beenden?
        ///Wenn sie es minimieren werden Änderungen weiter im Hintergrund veröffentlicht..
        /// </summary>
        internal static string CloseConfirmationDialog_Content {
            get {
                return ResourceManager.GetString("CloseConfirmationDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programm beenden.
        /// </summary>
        internal static string CloseConfirmationDialog_Title {
            get {
                return ResourceManager.GetString("CloseConfirmationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie das Programm wirklich beenden? Änderungen werden dann nicht mehr veröffentlicht..
        /// </summary>
        internal static string ExitConfirmationDialog_Content {
            get {
                return ResourceManager.GetString("ExitConfirmationDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programm beenden.
        /// </summary>
        internal static string ExitConfirmationDialog_Title {
            get {
                return ResourceManager.GetString("ExitConfirmationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dies ist ein Helfer-Programm, um den Online-Vertretungsplan zu aktualisieren. Es arbeitet selbstständig im Hintergrund und lädt neue Versionen automatisch hoch, das Hochladen kann aber auch manuell gestartet werden.
        ///
        ///Bei Fragen wenden Sie sich bitte an Dominik Stiller (domi.stiller@gmail.com)..
        /// </summary>
        internal static string InfoDialog_Content {
            get {
                return ResourceManager.GetString("InfoDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen über das Programm.
        /// </summary>
        internal static string InfoDialog_Title {
            get {
                return ResourceManager.GetString("InfoDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Dateifehler aufgetreten. Möglicherweise wird die ausgewählte Datei gerade von einem anderen Programm verwendet. Der Vertretungsplan wurde nicht veröffentlicht..
        /// </summary>
        internal static string IOExceptionDialog_Content {
            get {
                return ResourceManager.GetString("IOExceptionDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vertretungsplan wurde erfolgreich veröffentlicht. Die Änderungen werden bald online angezeigt..
        /// </summary>
        internal static string PublishSuccessDialog_Content {
            get {
                return ResourceManager.GetString("PublishSuccessDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veröffentlichen erfolgreich.
        /// </summary>
        internal static string PublishSuccessDialog_Title {
            get {
                return ResourceManager.GetString("PublishSuccessDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veröffentliche....
        /// </summary>
        internal static string Status_Publishing {
            get {
                return ResourceManager.GetString("Status_Publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überwache auf Änderungen....
        /// </summary>
        internal static string Status_Watching {
            get {
                return ResourceManager.GetString("Status_Watching", resourceCulture);
            }
        }
    }
}
